language: ruby
cache: bundler
script: bundle
deploy:
  - provider: script
    script: bundle exec rake stage
    on:
      condition: "$TRAVIS_BRANCH" != "master"
  - provider: script
    script: bundle exec rake release
    on:
      branch: master
