dist: trusty
language: ruby
cache: bundler
script:
  - gem install -v 1.16.1 bundler --no-rdoc --no-ri
  - bundle exec rake build
deploy:
  provider: script
  skip_cleanup: true
  script: gem install s3_website && s3_website push
  on:
    all_branches: true
